language: c
dist: xenial
os: linux

env:
  global:
    - ROCKSPEC=rockspecs/lua-fmt-scm-1.rockspec
  jobs:
    - LUA="lua 5.1"
    - LUA="lua 5.2"
    - LUA="lua 5.3"
    - LUA="lua 5.4"
    - LUA="luajit 2.0"
    - LUA="luajit 2.1"

branches:
  only:
    - master

before_install:
  - pip install --user urllib3[secure] cpp-coveralls
  - curl -O https://raw.githubusercontent.com/luarocks/hererocks/master/hererocks.py
  - python hererocks.py env --$LUA -rlatest
  - source env/bin/activate

install:
  - luarocks make $ROCKSPEC CFLAGS="-O3 -fPIC -Wall -Wextra --coverage" LIBFLAG="-shared --coverage"

script: 
  - lua test.lua

after_success:
    - coveralls

notifications:
  email:
    on_success: change
    on_failure: always

# vim: ft=yaml nu et sw=2 fdc=2 fdm=syntax
